### ISSUE TITLE
TODOs left for Contao 4.9.0

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1309]
- [x] Consistently use "backup codes" instead of "recovery codes" (see #1320)
- [x] Check if disabling 2FA clears the backup codes and trusted devices (see #1322)
- [x] Adjust the SERP widget to the new Google design (see #1323)
- [x] Fix rendering the picker preview (see #1327)

<img width="532" alt="" src="https://user-images.githubusercontent.com/1192057/74243895-d77e8600-4ce0-11ea-88de-223bb188bb64.png">

**Comment by asaage** [comment]
> Adjust the SERP widget to the new Google design (and maybe rename it to "SERP preview" without "Google" again?)

do you really want to keep up with googles designchanges?
they went from no-favicons, green-urls to favicons with breadcrumbs and no green at all and back to no favicons within a couple of weeks. And i assume the widget doesn't even consider richsnippets which google might find on the site.
Apart from that google often does not even use the meta-description but text that is more ~~appropiate and~~ in neighbourhood of the search-term.

**Comment by contaoacademy** [comment]
Ich fände es schön, wenn der Text der Checkbox beim Crawler "Nach kaputten Links suchen" noch anders benannt wird.
Das Wort "kaputt" ist umgangssprachlich.

Wie wäre es mit "Nach fehlerhaften oder defekten Links suchen"

**Comment by leofeyer** [comment]
> Wie wäre es mit "Nach fehlerhaften oder defekten Links suchen"

Ich habe die deutsche Übersetzung entsprechend angepasst.
