### ISSUE TITLE
Road to Symfony 5

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1889]
This is a list of packages that `contao/contao` currently requires and that are not compatible with Symfony 5 yet.

* [x] [contao/manager-plugin](https://packagist.org/packages/contao/manager-plugin) → see https://github.com/contao/manager-plugin/pull/26
* [x] [contao/monorepo-tools](https://packagist.org/packages/contao/monorepo-tools) → see https://github.com/contao/monorepo-tools/pull/4
* [x] [contao/phpstan](https://packagist.org/packages/contao/phpstan) → fixed in version 0.12.6
* [x] [terminal42/service-annotation-bundle](https://packagist.org/packages/terminal42/service-annotation-bundle) → fixed in version 1.0.1
* [x] [doctrine/doctrine-cache-bundle](https://packagist.org/packages/doctrine/doctrine-cache-bundle) → see #1916
* [x] [knplabs/knp-menu-bundle](https://packagist.org/packages/knplabs/knp-menu-bundle) → see #1893
* [x] [lexik/maintenance-bundle](https://packagist.org/packages/lexik/maintenance-bundle) → see #1930
* [x] [nelmio/cors-bundle](https://packagist.org/packages/nelmio/cors-bundle) → see #1893

Here is the filtered output of the `composer why` command:

```
symfony/config
contao/manager-plugin          2.8.1       requires  symfony/config (^3.3 || ^4.0)
contao/monorepo-tools          dev-master  requires  symfony/config (^3.4 || ^4.0)

symfony/console
contao/monorepo-tools          dev-master  requires  symfony/console (^3.4 || ^4.0)

symfony/debug
contao/phpstan         0.12.5      requires  symfony/debug (^4.4)

symfony/dependency-injection
contao/manager-plugin                 2.8.1       requires  symfony/dependency-injection (^3.3 || ^4.0)
terminal42/service-annotation-bundle  1.0.0       requires  symfony/dependency-injection (^4.0)

symfony/doctrine-bridge
doctrine/doctrine-cache-bundle  1.4.0       requires  symfony/doctrine-bridge (^3.4|^4.0)

symfony/filesystem
contao/manager-plugin         2.8.1       requires  symfony/filesystem (^3.3 || ^4.0)
contao/monorepo-tools         dev-master  requires  symfony/filesystem (^3.4 || ^4.0)

symfony/framework-bundle
knplabs/knp-menu-bundle              v2.3.0      requires  symfony/framework-bundle (^3.4 | ^4.0)
lexik/maintenance-bundle             v2.1.5      requires  symfony/framework-bundle (~2.7|~3.0|^4.0)
nelmio/cors-bundle                   1.5.6       requires  symfony/framework-bundle (^2.7 || ^3.0 || ^4.0)

symfony/http-kernel
contao/manager-plugin                 2.8.1       requires  symfony/http-kernel (^3.3 || ^4.0)
terminal42/service-annotation-bundle  1.0.0       requires  symfony/http-kernel (^4.0)

symfony/monolog-bridge
contao/phpstan          0.12.5      requires  symfony/monolog-bridge (^4.4)

symfony/process
contao/monorepo-tools      dev-master  requires  symfony/process (^3.4 || ^4.0)

symfony/routing
contao/manager-plugin        2.8.1       requires  symfony/routing (^3.3 || ^4.0)

symfony/templating
contao/phpstan           0.12.5   requires  symfony/templating (^4.4)

symfony/translation
lexik/maintenance-bundle  v2.1.5      requires  symfony/translation (~2.7|~3.0|^4.0)

symfony/yaml
contao/monorepo-tools          dev-master  requires  symfony/yaml (^3.4 || ^4.0)
```

**Comment by leofeyer** [comment]
We will also have to change `"doctrine/doctrine-bundle": "^1.8"` to `"doctrine/doctrine-bundle": "^1.8 || ^2.0"` and `"doctrine/doctrine-migrations-bundle": "^1.1"` to `"doctrine/doctrine-migrations-bundle": "^1.1 || ^2.0 || ^3.0"` (if compatible).

And of course `"4.4.*"` to `"4.4.* || 5.1.*"` for all Symfony packages.

**Comment by fritzmg** [comment]
As mentioned in https://github.com/contao/contao/pull/1829 I'd also like to discuss whether we can allow installation of _specific_ symfony components in higher versions, rather than limiting all of `symfony/*` to one particular minor version.

**Comment by leofeyer** [comment]
Please create a separate issue for that.

**Comment by m-vo** [comment]
`lexik/maintenance-bundle` looks quite abandonded (the last commit is from Feb 14, 2018 and no activity since), although a [PR for SF5](https://github.com/lexik/LexikMaintenanceBundle/pull/91) is already there.

**Comment by ausi** [comment]
PR for monorepo-tools: https://github.com/contao/monorepo-tools/pull/4

**Comment by leofeyer** [comment]
The Doctrine Cache Bundle [has been deprecated](https://github.com/doctrine/DoctrineCacheBundle/issues/156) and there will not be a Symfony 5 version, therefore we have to use `symfony/cache` instead.

```yaml
doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        query_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        result_cache_driver:
            type: service
            id: doctrine.result_cache_provider

services:
    doctrine.result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
```

The example above is taken from the [Symfony recipe](https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/config/packages/prod/doctrine.yaml).

**Comment by leofeyer** [comment]
Regarding the Lexik maintenance bundle: As discussed in Mumble on July 2nd, we want to fork the package and merge the [Symfony 5 PR](https://github.com/lexik/LexikMaintenanceBundle/pull/91) into the fork. In the long run, we want to get rid of the bundle and implement new solutions for two maintenance cases:

1. Disable the application (e.g. during deployment or DB updates)

Possible implementation: The entry point reads an environment variable with a path to a static file. If the environment variable is set and the file exists, it should be sent to the client (bypassing the application completely).

2. Disable a website root page (e.g. while building a language-specific part of the site)

Possible implementation: Add a checkbox select menu with all root pages to the maintenance module and allow to enable maintenance mode per root page. Show a warning if one or more pages are in maintenance mode.

**Comment by leofeyer** [comment]
Regarding the last step – namely making Contao itself compatible with Symfony 5.1 – I have begun a PR in #1941. I am therefore closing this ticket now.
