### ISSUE TITLE
PHP 8.0 Roadmap

### ISSUE THREAD

**Issue by ausi** [contao/contao#2263]
The planned release date for PHP 8.0 is December 3rd.  
8.0.0-RC1 is planned for September 17th.

Contao 4.9, 4.10 and 4.11 will be compatible with PHP 8.0.  
Contao 4.4 will not be compatible.

### ToDos (to be extended):

- [x] Agree on `^7.2 || ^8.0` vs. `>=7.2` (see https://github.com/sebastianbergmann/phpunit/commit/fa50b8949b6f2f98a614fe66f54c5e6ea6a0f078 for example). Result: `^7.2 || ^8.0`
- [x] Check all dependencies and add incompatible ones to this list.

Our packages:
- [x] `ausi/slug-generator` add compatibility and release new version https://github.com/ausi/slug-generator/pull/23
- [x] `toflar/psr6-symfony-http-cache-store` add compatibility and release new version https://github.com/Toflar/psr6-symfony-http-cache-store/pull/36
- [x] `terminal42/escargot` add compatibility and release new version https://github.com/terminal42/escargot/pull/18
- [x] `terminal42/service-annotation-bundle` add compatibility and release new version https://github.com/terminal42/service-annotation-bundle/issues/5
- [x] `‌contao/image` add compatibility and release new version https://github.com/contao/image/pull/74
- [x] `contao/imagine-svg` (is already compatible)
- [x] `contao/manager-plugin` add compatibility and release new version https://github.com/contao/manager-plugin/pull/36
- [x] `contao/maintenance-bundle-deprecated` add compatibility and release new version https://github.com/contao/maintenance-bundle-deprecated/pull/1
- [x] `contao/mobile-page-layout-bundle` add compatibility and release new version https://github.com/contao/mobile-page-layout-bundle/pull/5
- [x] `contao/tcpdf-bundle` add compatibility and release new version https://github.com/contao/tcpdf-bundle/pull/1
- [x] `contao/easy-coding-standard` add compatibility and release new version https://github.com/contao/easy-coding-standard/issues/6
- [x] `contao/phpstan` add compatibility and release new version https://github.com/contao/phpstan/pull/20
- [x] `contao/test-case` add compatibility and release new version https://github.com/contao/test-case/issues/9
- [x] `contao/monorepo-tools` add compatibility (no release necessary) https://github.com/contao/monorepo-tools/pull/6
- [x] `contao/managed-edition` add compatibility and release new version https://github.com/contao/managed-edition/issues/56
- [x] `contao/deployer-edition` ~~add compatibility~~ (no longer maintained)
- [x] `contao/contao` and all subpackages (probably the final step) bugfixes PR: #2535
- [x] `contao-components/installer` https://github.com/contao-components/installer/issues/6

Third party:
- [x] `phpunit/php-token-stream` We need to update to version `^4.0` #2281
- [x] `spomky-labs/otphp` We need to update to `^10.0` #2281
- [x] `imagine/imagine` https://github.com/avalanche123/Imagine/pull/740
- [x] `bacon/bacon-qr-code` https://github.com/Bacon/BaconQrCode/pull/74
- [x] `beberlei/assert` https://github.com/beberlei/assert/issues/301
- [x] `doctrine/dbal`
- [x] `doctrine/doctrine-cache-bundle` We need to get rid of this bundle because it is abandoned and doesn’t support PHP 8. #2534
- [x] `doctrine/migrations` https://github.com/doctrine/migrations/pull/980
- [x] `doctrine/orm` https://github.com/doctrine/orm/pull/8303
- [x] `doctrine/reflection` https://github.com/doctrine/reflection/pull/49
- [x] `dragonmantank/cron-expression` https://github.com/dragonmantank/cron-expression/issues/92
- [x] `friendsofsymfony/http-cache` https://github.com/FriendsOfSymfony/FOSHttpCache/issues/487
- [x] `friendsofsymfony/http-cache-bundle` (depends on one line above)
- [x] `knplabs/knp-menu-bundle` https://github.com/KnpLabs/KnpMenuBundle/pull/430
- [x] `knplabs/knp-time-bundle` https://github.com/KnpLabs/KnpTimeBundle/issues/147
- [x] `lcobucci/jwt` https://github.com/lcobucci/jwt/pull/324 We need to update to version ^4.0 https://github.com/contao/contao/pull/2617
- [x] `nyholm/psr7` https://github.com/Nyholm/psr7/pull/151
- [x] `ocramius/proxy-manager` https://github.com/Ocramius/ProxyManager/pull/628 (and `zendframework/zend-code` and `zendframework/zend-eventmanager`)
- [x] `php-http/message` https://github.com/php-http/message/pull/129
- [x] `symfony-cmf/routing` https://github.com/symfony-cmf/Routing/pull/255
- [x] `symfony-cmf/routing-bundle` https://github.com/symfony-cmf/routing-bundle/issues/456
- [x] `ua-parser/uap-php` https://github.com/ua-parser/uap-php/issues/66

**Comment by ausi** [comment]
@contao/developers At which point is it OK to release PHP 8 compatible versions?
I think as soon as `8.0.0-RC1` got released we can start releasing compatible versions.

**Comment by aschempp** [comment]
The sooner the better, but it depends a lot on the environment and lots of packages, so I guess it will take a while…

**Comment by ausi** [comment]
I think we should start releasing our own depenencies early and only release `contao/contao` itself with php 8 support once all dependencies work with it too.

**Comment by m-vo** [comment]
> I think we should start releasing our own depenencies early and only release contao/contao itself with php 8 support once all dependencies work with it too.

Shouldn't composer handle this? Or do you think about possibly (wrong because incompatible) open php version constraints in 3rd party code that will break with php 8?

**Comment by ausi** [comment]
> Shouldn't composer handle this?

Yes, but IMO it doesn’t make sense to confuse everybody by stating that Contao is php 8 compatible even if our dependencies are not.

**Comment by ausi** [comment]
> Agree on `^7.2 || ^8.0` vs. `>=7.2`

It looks like Symfony and PHPUnit are in favor of using `>=` for the PHP requirement.

WDYT? Please use 👍 for `>=7.2` and 👎 for `^7.2 || ^8.0`

__EDIT:__ We agreed on using `^7.2 || ^8.0`

**Comment by leofeyer** [comment]
Make sure to also watch https://www.youtube.com/watch?v=c3bpTBjhK2Y&t=363s

**Comment by alcaeus** [comment]
Just a small heads up: the `doctrine/doctrine-cache-bundle` package has been abandoned and won't be updated to support PHP 8. It is a transitive dependency in DoctrineBundle 1.x, which has been removed in 2.0. Barring any other packages requiring it, you don't need to make any changes, but be aware that users on DoctrineBundle 1 won't be able to run PHP 8 until they upgrade to DoctrineBundle 2.

**Comment by Toflar** [comment]
@ausi: `terminal42/escargot` can be bumped to v 1.0.0 which comes with PHP 8 support :)

**Comment by ausi** [comment]
All internal and external packages have an associated ticket now. We now just need to fix all of them 😳

**Comment by m-vo** [comment]
PHP 8 promotes function arguments to become part of the API (named arguments).

Should we review and possibly adjust argument names across our codebase before they cannot be changed anymore? 
Or are we explicitly excluding argument names from our BC promise?

**Comment by Toflar** [comment]
> Or are we explicitly excluding argument names from our BC promise?

No way to provide BC for named arguments imho. So I would explicitly exclude it. It's pure nonsense.

**Comment by ausi** [comment]
> Should we review and possibly adjust argument names across our codebase before they cannot be changed anymore?

If we want to rename something. Now would certainly be the best time ☺️

We should probably also check if we use the same argument names as the interfaces we implement. Maybe there is a tool that can check for such things?

> No way to provide BC for named arguments imho. So I would explicitly exclude it. It's pure nonsense.

I’m not sure about that. Excluding it from our BC promise would mean that nobody can use named arguments with our API.

**Comment by m-vo** [comment]
>  Now would certainly be the best time

We could also do it like [Wordpress](https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/) and discourage the use of named arguments until explicitly stated (= review/audit finished).

> We should probably also check if we use the same argument names as the interfaces we implement. Maybe there is a tool that can check for such things?

This should imo go into to the cs fixer if possible.

**Comment by m-vo** [comment]
regarding https://github.com/contao/easy-coding-standard/issues/6

We could consider removing the code style and static analysis related composer dependencies and move on to a phive based approach or sth similar. We do not need the PHP-CS-Fixer to recognize PHP 8 code for instance but this transitive dependency is effectively blocking to use `contao/contao` with PHP 8. 

Edit: this would for instance look like this:

- `contao/easy-coding-standard`:
  - use `humbug/box` to create a phar (either in repo or only in workflow)
  - release workflow that builds the phar, [signs it](https://phar.io/howto/sign-and-upload-to-github.html) and [adds a release](https://github.com/actions/upload-release-asset) with it
  - one time PR adding it to https://github.com/phar-io/phar.io/blob/master/data/repositories.xml
- `contao/contao`
  - drop composer requirement
  - add phive requirement
  - update README/ci/composer scripts

**Comment by ausi** [comment]
Once #2617 is merged we can check the last box on the todo list 🎉

For the named arguments topic I created a seperate ticket: #2624

**Comment by bytehead** [comment]
PHP 8 is near! 🍻🚀

**Comment by leofeyer** [comment]
Eventually, Contao will be fully compatible with PHP 8 as of versions 4.9.11, 4.10.6 and 4.11.0! 🥳  It was quite an effort and I want to thank you all for your help. 🙏🏻
